version: 2.1

executors:
  default:
    working_directory: ~/repo
    docker:
      - image: circleci/node
        environment:
          TZ: Asia/Tokyo

commands:
  restore_yarn:
    steps:
      - restore_cache:
          name: Restore yarn dependencies
          key: yarn-v2-{{ checksum "package.json" }}
  save_yarn:
    steps:
      - save_cache:
          name: Cache yarn dependencies
          key: yarn-v2-{{ checksum "package.json" }}
          paths:
            - ~/repo/node_modules

jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - restore_yarn
      - run:
          name: Install yarn dependencies
          command: yarn install --frozen-lockfile
      - save_yarn
  lint:
    executor:
      name: default
    steps:
      - checkout
      - restore_yarn
      - run:
          name: Run lint
          command:
              mkdir -p /tmp/test-reports/eslint
              node_modules/.bin/eslint . --format junit --output-file /tmp/test-reports/eslint/results.xml
      - store_test_results:
          path: /tmp/test-reports

workflows:
  linting:
    jobs:
      - setup
      - lint:
          requires:
            - setup