version: 2.1

executors:
  default:
    working_directory: ~/repo
    docker:
      - image: circleci/node
        environment:
          TZ: Asia/Tokyo
jobs:
  lint:
    executor:
      name: default
    steps:
      - checkout
      - restore_yarn
      - run:
          name: Run lint
          command: yarn run lint

workflows:
  linting:
    jobs:
      - lint: