version: 2.1

executors:
  default:
    working_directory: ~/repo
    docker:
      - image: circleci/node
        environment:
          TZ: Asia/Tokyo

commands:
  restore_yarn:
    steps:
      - restore_cache:
          name: Restore yarn dependencies
          key: yarn-{{ checksum "package.json" }}
  save_yarn:
    steps:
      - save_cache:
          name: Cache yarn dependencies
          key: yarn-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
  run:
    steps:
      - run:
          name: Install yarn dependencies
          command: yarn install --frozen-lockfile
jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - restore_yarn
      - run
      - save_yarn
  lint:
    executor:
      name: default
    steps:
      - checkout
      - restore_yarn
      - run_lint:
          name: Run lint
          command: yarn run lint

workflows:
  linting:
    jobs:
      - setup
      - lint:
          requires:
            - setup